### ISSUE TITLE
Support for gitlab release URLs

### ISSUE THREAD

**Issue by Jaakkonen** [fosskers/cargo-aur#1]
Currently the PKGBUILD assumes that the assets are at `<REPO>/releases/download/v<VERSION>/<NAME>-<VERSION>-x86_64.tar.gz`.

However with Gitlab the assets are at `<REPO>/-/archive/<TAG>/<ARTIFACT NAME>`.

There could be a option to override these templates in the cmdline/environment variables.

**Comment by fosskers** [comment]
Reasonable! Let me get on that.

**Comment by fosskers** [comment]
The linked PR produces links like:
```
source=("https://gitlab.com/fosskers/cargo-aur/-/archive/v$pkgver/cargo-aur-$pkgver-x86_64.tar.gz")
```
Would that work for you? It now auto-detects which git host is set in the `repository` field of `Cargo.toml`, so no extra CLI flag was needed.

**Comment by fosskers** [comment]
Hi there, I'm going to go ahead with this so that I can add further improvements to the project. Let me know if it doesn't do what you were expecting, and I'll patch it again.
