### ISSUE TITLE
Add support for differing binary names

### ISSUE THREAD

**Issue by hisbaan** [fosskers/cargo-aur#12]
For example, my package, `didyoumean` builds a binary called `dym` with this addition to the `Cargo.toml` file:

```toml
[[bin]]
name = "dym"
path = "src/main.rs"
```

The script fails when running `strip` as the binary name is not as the script expects. The issue is with line 246 of main.rs: `binary.push(&package.name);` which assumes that `package.name` is the same as the produced binary. 

I don't know enough about `Cargo.toml` parsing so I'm not sure how to parse a new field exactly and to change the binary path optionally if that field exists, however I would be glad to work on it if someone could point me in the right direction.

**Comment by fosskers** [comment]
This would be an easy fix for me, let me take care of it. Thanks for bringing this to my attention.

**Comment by hisbaan** [comment]
Awesome! Thank you so much :) It's a relatively niche configuration I suppose

**Comment by fosskers** [comment]
I've put up a PR that implements this.
