### ISSUE TITLE
Output to target/

### ISSUE THREAD

**Issue by iamwacko** [fosskers/cargo-aur#14]
Most Rust packaging and building tools (cargo, cargo-bundle, cargo-deb, etc.) output somewhere in the target directory. It would be wonderful if cargo-aur would do the same. I could make a PR if you don't want to do this yourself.

**Comment by fosskers** [comment]
As in, `target/aur/`?

**Comment by iamwacko** [comment]
Yeah

**Comment by fosskers** [comment]
I haven't forgotten about this; I intend to make this change.

**Comment by fosskers** [comment]
Sorry for the wait!

**Comment by iamwacko** [comment]
> Sorry for the wait!

No worries, similar things have happened to me before. At this point, I've actually gotten pretty good at writing PKGBUILDs by hand.

**Comment by fosskers** [comment]
Released as `1.6.0`.
