### ISSUE TITLE
Use SPDX license identifier

### ISSUE THREAD

**Issue by chenrui333** [fosskers/cargo-aur#16]
👋 It looks like the license identifier references are outdated from the [SPDX identifier perspective](https://spdx.org/licenses/). Would be good to use SDPX license identifier (as it is a ISO standard). Let me know if that makes sense. Thanks!

https://github.com/fosskers/cargo-aur/blob/c2661279b701f061056defca6902d184eeafc3e6/src/main.rs#L20-L22

**Comment by fosskers** [comment]
You're right, let me double-check this. Thanks for reporting.

**Comment by fosskers** [comment]
Fixed. Thanks again for the report.
