### ISSUE TITLE
Fails for singular author

### ISSUE THREAD

**Issue by xeruf** [fosskers/cargo-aur#27]
https://github.com/Colonial-Dev/vcard-qr
````
❯ cargo aur
:: Error: TOML parse error at line 1, column 1
  |
1 | [package]
  | ^^^^^^^^^
missing field `authors`
```
I had to rename `author` and turn it into an array, maybe that can be supported?

**Comment by fosskers** [comment]
The official field name is a plural `authors`: https://doc.rust-lang.org/cargo/reference/manifest.html#the-authors-field

**Comment by xeruf** [comment]
You are correct, adjusted the package

**Comment by fosskers** [comment]
@horberlan Can you be a bit more specific?

**Comment by horberlan** [comment]
Hi @fosskers! autors field is deprecated: https://doc.rust-lang.org/cargo/reference/manifest.html#the-authors-field
maybe another way to link authors?

**Comment by fosskers** [comment]
> is deprecated
Hm, in favour of what, I wonder? They don't mention an alternative.

**Comment by GeoffClements** [comment]
When creating a debian package, under `package.metadata.deb`, it is possible to have a `maintainer` field. Perhaps something similar could be used here?
