### ISSUE TITLE
Binaries are stripped by default

### ISSUE THREAD

**Issue by murlakatamenka** [fosskers/cargo-aur#3]
Hi, I think

```sh
options=("strip")
```

isn't necessary because `strip` is default option in `/etc/makepkg.conf`. And if it's not, user's config should be respected.

No big deal, but feedback is usually welcome, so there it is :smile:

**Comment by fosskers** [comment]
Looks like you're right! I'll take it out, thanks for the suggestion.

**Comment by fosskers** [comment]
Done.

**Comment by murlakatamenka** [comment]
Thanks,  that was fast! :+1:
